# Dragon Real Estate - Price Predictor

In [1]:
import pandas as pd

In [2]:
housing = pd.read_csv("data.csv")

In [3]:
housing.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  PTRATIO  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

        B  LSTAT  MEDV  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7  
3  394.63   2.94  33.4  
4  396.90   5.33  36.2

In [4]:
housing.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   CRIM     506 non-null    float64
 1   ZN       506 non-null    float64
 2   INDUS    506 non-null    float64
 3   CHAS     506 non-null    int64  
 4   NOX      506 non-null    float64
 5   RM       502 non-null    float64
 6   AGE      506 non-null    float64
 7   DIS      506 non-null    float64
 8   RAD      506 non-null    int64  
 9   TAX      506 non-null    int64  
 10  PTRATIO  506 non-null    float64
 11  B        506 non-null    float64
 12  LSTAT    506 non-null    float64
 13  MEDV     506 non-null    float64
dtypes: float64(11), int64(3)
memory usage: 55.5 KB


In [5]:
# To see value count of a column
housing["CHAS"].value_counts()

0    471
1     35
Name: CHAS, dtype: int64

In [6]:
housing.describe()

CRIM          ZN       INDUS        CHAS         NOX          RM  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  502.000000   
mean     3.613524   11.363636   11.136779    0.069170    0.554695    6.286853   
std      8.601545   23.322453    6.860353    0.253994    0.115878    0.704727   
min      0.006320    0.000000    0.460000    0.000000    0.385000    3.561000   
25%      0.082045    0.000000    5.190000    0.000000    0.449000    5.885500   
50%      0.256510    0.000000    9.690000    0.000000    0.538000    6.209000   
75%      3.677083   12.500000   18.100000    0.000000    0.624000    6.628000   
max     88.976200  100.000000   27.740000    1.000000    0.871000    8.780000   

              AGE         DIS         RAD         TAX     PTRATIO           B  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean    68.574901    3.795043    9.549407  408.237154   18.455534  356.674032   
std     28.148861    2.105710    8.707259  168.537116    2.164946   91.294864   
min      2.900000    1.129600    1.000000  187.000000   12.600000    0.320000   
25%     45.025000    2.100175    4.000000  279.000000   17.400000  375.377500   
50%     77.500000    3.207450    5.000000  330.000000   19.050000  391.440000   
75%     94.075000    5.188425   24.000000  666.000000   20.200000  396.225000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

            LSTAT        MEDV  
count  506.000000  506.000000  
mean    12.653063   22.532806  
std      7.141062    9.197104  
min      1.730000    5.000000  
25%      6.950000   17.025000  
50%     11.360000   21.200000  
75%     16.955000   25.000000  
max     37.970000   50.000000

In [7]:
%matplotlib inline
# import matplotlib.pyplot as plt
# # Plot histogram
# housing.hist(bins=50, figsize=(20,15))

# Train - Test Splitting

In [8]:
import numpy as np
# # Split into train/test data
# def split_train_test(data, test_ratio):
#     np.random.seed(42) # To get same value every time
#     shuffled = np.random.permutation(len(data))
#     test_set_size = int(len(data)*test_ratio)
#     test_indices = shuffled[:test_set_size]
#     train_indices = shuffled[test_set_size:]
#     return data.iloc[train_indices], data.iloc[test_indices]


In [9]:
# train_set, test_set = split_train_test(housing, 0.2)

In [10]:
# print(f"Rows in train set: {len(train_set)}, Rows in test set: {len(test_set)}")

# Train test split using sklearn

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
train_set, test_set = train_test_split(housing, test_size=0.2, random_state =42)

In [13]:
print(f"Rows in train set: {len(train_set)}, Rows in test set: {len(test_set)}")

Rows in train set: 404, Rows in test set: 102


In [14]:
# To distribute train-test evenly, so that every cateogry is in both train and test data
from sklearn.model_selection import StratifiedShuffleSplit
split = StratifiedShuffleSplit (n_splits=1, test_size = 0.2, random_state = 42)
for train_index, test_index in split.split(housing, housing['CHAS']):
    strat_train_set = housing.loc[train_index]
    strat_test_set = housing.loc[test_index]

In [15]:
strat_test_set["CHAS"].value_counts()

0    95
1     7
Name: CHAS, dtype: int64

In [16]:
# Now housing dataframe consist only train_set
housing=strat_train_set.copy()

# Looking for correlations

In [17]:
corr_matrix = housing.corr()

In [18]:
# To check relation of columns with other columns
corr_matrix['MEDV'].sort_values(ascending = False)

MEDV       1.000000
RM         0.679048
B          0.361761
ZN         0.339741
DIS        0.240451
CHAS       0.205066
AGE       -0.364596
RAD       -0.374693
CRIM      -0.393715
NOX       -0.422873
TAX       -0.456657
INDUS     -0.473516
PTRATIO   -0.493534
LSTAT     -0.740494
Name: MEDV, dtype: float64

In [19]:
# # For creating correlation plot
# from pandas.plotting import scatter_matrix
# attributes = ["RM", "ZN", "MEDV", "LSTAT"]
# scatter_matrix(housing[attributes], figsize=(12,8))

In [20]:
# housing.plot(kind = 'scatter', x = "RM", y = "MEDV", alpha =0.7)

# Trying to Attribute Combination


In [21]:
# housing["TAXRM"]= housing['TAX']/housing['RM']

In [22]:
housing.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  \
254  0.04819  80.0   3.64     0  0.392  6.108  32.0  9.2203    1  315   
348  0.01501  80.0   2.01     0  0.435  6.635  29.7  8.3440    4  280   
476  4.87141   0.0  18.10     0  0.614  6.484  93.6  2.3053   24  666   
321  0.18159   0.0   7.38     0  0.493  6.376  54.3  4.5404    5  287   
326  0.30347   0.0   7.38     0  0.493  6.312  28.9  5.4159    5  287   

     PTRATIO       B  LSTAT  MEDV  
254     16.4  392.89   6.57  21.9  
348     17.0  390.94   5.99  24.5  
476     20.2  396.21  18.68  16.7  
321     19.6  396.90   6.87  23.1  
326     19.6  396.90   6.15  23.0

In [23]:
corr_matrix = housing.corr()
# To check relation of columns with other columns
corr_matrix['MEDV'].sort_values(ascending = False)

MEDV       1.000000
RM         0.679048
B          0.361761
ZN         0.339741
DIS        0.240451
CHAS       0.205066
AGE       -0.364596
RAD       -0.374693
CRIM      -0.393715
NOX       -0.422873
TAX       -0.456657
INDUS     -0.473516
PTRATIO   -0.493534
LSTAT     -0.740494
Name: MEDV, dtype: float64

In [24]:
# housing.plot(kind = 'scatter', x = "TAXRM", y = "MEDV", alpha =0.7)

In [25]:
housing = strat_train_set.drop("MEDV", axis =1)
housing_labels = strat_train_set["MEDV"].copy()

# Missing attributes 

In [26]:
# To take care of missing attributes, we have three options:
#     1. Get rid of the missing points.
#     2. Get rid of whole attribute
#     3. Set the values to some value i.e., (0, mean or median).



In [27]:
a = housing.dropna(subset=["RM"]) # option 1
a.shape

(400, 13)

In [28]:
b = housing.drop("RM", axis =1) # option 2
b.head()  # No RM column

CRIM    ZN  INDUS  CHAS    NOX   AGE     DIS  RAD  TAX  PTRATIO  \
254  0.04819  80.0   3.64     0  0.392  32.0  9.2203    1  315     16.4   
348  0.01501  80.0   2.01     0  0.435  29.7  8.3440    4  280     17.0   
476  4.87141   0.0  18.10     0  0.614  93.6  2.3053   24  666     20.2   
321  0.18159   0.0   7.38     0  0.493  54.3  4.5404    5  287     19.6   
326  0.30347   0.0   7.38     0  0.493  28.9  5.4159    5  287     19.6   

          B  LSTAT  
254  392.89   6.57  
348  390.94   5.99  
476  396.21  18.68  
321  396.90   6.87  
326  396.90   6.15

In [29]:
# Replace missing values by median
median= housing["RM"].median()

In [30]:
median

6.2135

In [31]:
housing["RM"].fillna(median) # Option 3

254    6.108
348    6.635
476    6.484
321    6.376
326    6.312
       ...  
155    6.152
423    6.103
98     7.820
455    6.525
216    5.888
Name: RM, Length: 404, dtype: float64

In [32]:
housing.describe() #to see the description before imputing

CRIM          ZN       INDUS        CHAS         NOX          RM  \
count  404.000000  404.000000  404.000000  404.000000  404.000000  400.000000   
mean     3.602814   10.836634   11.344950    0.069307    0.558064    6.282645   
std      8.099383   22.150636    6.877817    0.254290    0.116875    0.715714   
min      0.006320    0.000000    0.740000    0.000000    0.389000    3.561000   
25%      0.086962    0.000000    5.190000    0.000000    0.453000    5.878750   
50%      0.286735    0.000000    9.900000    0.000000    0.538000    6.213500   
75%      3.731923   12.500000   18.100000    0.000000    0.631000    6.632000   
max     73.534100  100.000000   27.740000    1.000000    0.871000    8.780000   

              AGE         DIS         RAD         TAX     PTRATIO           B  \
count  404.000000  404.000000  404.000000  404.000000  404.000000  404.000000   
mean    69.039851    3.746210    9.735149  412.341584   18.473267  353.392822   
std     28.258248    2.099057    8.731259  168.672623    2.129243   96.069235   
min      2.900000    1.129600    1.000000  187.000000   13.000000    0.320000   
25%     44.850000    2.035975    4.000000  284.000000   17.400000  374.617500   
50%     78.200000    3.122200    5.000000  337.000000   19.000000  390.955000   
75%     94.100000    5.100400   24.000000  666.000000   20.200000  395.630000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

            LSTAT  
count  404.000000  
mean    12.791609  
std      7.235740  
min      1.730000  
25%      6.847500  
50%     11.570000  
75%     17.102500  
max     36.980000

In [33]:
# to replace missing values to median at every place i.e., test_set, train_set, new_datas
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy="median")
imputer.fit(housing)

SimpleImputer(strategy='median')

In [34]:
# To see the computed values
imputer.statistics_ # display median for every column

array([2.86735e-01, 0.00000e+00, 9.90000e+00, 0.00000e+00, 5.38000e-01,
       6.21350e+00, 7.82000e+01, 3.12220e+00, 5.00000e+00, 3.37000e+02,
       1.90000e+01, 3.90955e+02, 1.15700e+01])

In [35]:
imputer.statistics_.shape

(13,)

In [36]:
X = imputer.transform(housing)

In [37]:
# Since X is an numpy array so we cannot use pandas methods on that so we craete a pandas dataframe
housing_tr = pd.DataFrame(X, columns=housing.columns)

In [38]:
housing_tr.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 404 entries, 0 to 403
Data columns (total 13 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   CRIM     404 non-null    float64
 1   ZN       404 non-null    float64
 2   INDUS    404 non-null    float64
 3   CHAS     404 non-null    float64
 4   NOX      404 non-null    float64
 5   RM       404 non-null    float64
 6   AGE      404 non-null    float64
 7   DIS      404 non-null    float64
 8   RAD      404 non-null    float64
 9   TAX      404 non-null    float64
 10  PTRATIO  404 non-null    float64
 11  B        404 non-null    float64
 12  LSTAT    404 non-null    float64
dtypes: float64(13)
memory usage: 41.2 KB


# Scikit-learn Design

Primarily, three types of objects
1. Estimators: It estimates some parameter based on a dataset. Ex. imputerIt has a fit method and transform method.  Fit method: Fits the dataset and calculates internal parameters

2. Transformers: transform methods takes input and return output based on the learnings from fit(). It also has a convenience called fit_transform() which fits and then transform.

3. predictors: LinearRegression model is an example of predictor. fit() and predict() are two common functions. It also gives score functions which evaluate the predictions.

# Feature Scaling

Primarily, two types of feature scaling methods:
1. Min-max scaling (Normalization) 
   (Value - min)/(max - min), for this sklearn provides a class called MinMaxScaler.
   
2. Standardization
   (Value - mean)/(std), for this sklearn provides a class called StandardScaler


# Creating a Pipeline

In [39]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
# Pipeline takes a list
my_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy = "median")),
    # .... add as many as you want in your pipeline
    ('std_scaler', StandardScaler()),
])


In [40]:
housing_num_tr = my_pipeline.fit_transform(housing)

In [41]:
housing_num_tr #Result is an numpy array, predictors use numpy array as input

array([[-0.43942006,  3.12628155, -1.12165014, ..., -0.97491834,
         0.41164221, -0.86091034],
       [-0.44352175,  3.12628155, -1.35893781, ..., -0.69277865,
         0.39131918, -0.94116739],
       [ 0.15682292, -0.4898311 ,  0.98336806, ...,  0.81196637,
         0.44624347,  0.81480158],
       ...,
       [-0.43525657, -0.4898311 , -1.23083158, ..., -0.22254583,
         0.41831233, -1.27603303],
       [ 0.14210728, -0.4898311 ,  0.98336806, ...,  0.81196637,
        -3.15239177,  0.73869575],
       [-0.43974024, -0.4898311 ,  0.37049623, ..., -0.97491834,
         0.41070422,  0.09940681]])

# Selecting a desired model for Real Dragon Estate

In [42]:
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
# model = LinearRegression()
model = RandomForestRegressor()
model.fit(housing_num_tr, housing_labels)

RandomForestRegressor()

In [43]:
some_data = housing.iloc[:5]

In [44]:
some_labels = housing_labels.iloc[:5]

In [45]:
prepared_data = my_pipeline.transform(some_data)

In [46]:
model.predict(prepared_data)

array([22.52 , 25.737, 16.818, 23.274, 23.462])

In [47]:
list(some_labels)

[21.9, 24.5, 16.7, 23.1, 23.0]

# Evaluating the model

In [48]:
from sklearn.metrics import mean_squared_error
housing_prediction = model.predict(housing_num_tr)
lin_mse = mean_squared_error(housing_labels, housing_prediction)
lin_rmse = np.sqrt(lin_mse)

In [49]:
lin_mse

1.4386972549504926

In [50]:
lin_rmse

1.1994570667391529

# Decision Tree Regression

from above it is clear that linear regression is not the accurate algo for this dataset so that model is discarded and we try decision tree algo on same data in search of a better model

In [51]:
# from sklearn.linear_model import LinearRegression
# from sklearn.tree import DecisionTreeRegressor
# model = DecisionTreeRegressor()
# model.fit(housing_num_tr, housing_labels)

In [52]:
# some_data = housing.iloc[:5]
# some_labels = housing_labels.iloc[:5]
# prepared_data = my_pipeline.transform(some_data)
# model.predict(prepared_data)
# list(some_labels)

In [53]:
# from sklearn.metrics import mean_squared_error
# housing_prediction = model.predict(housing_num_tr)
# mse = mean_squared_error(housing_labels, housing_prediction)
# rmse = np.sqrt(mse)

In [54]:
# mse

# Using better Evaluation technique - Cross Validation

In cross validation we divide train set in some parts i.e., 10 parts then firstly train on 9 sets and test one do this with all the 10 subsets one by one 

In [55]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(model, housing_num_tr, housing_labels, scoring = "neg_mean_squared_error", cv = 10) # cv is to select number of folds
rmse = np.sqrt(-scores)

In [56]:
rmse

array([2.84767389, 2.73038741, 4.44713298, 2.65851535, 3.50598463,
       2.65630269, 4.63951718, 3.33798607, 3.36997338, 3.16789405])

In [57]:
def print_scores(scores):
    print("Scores are :", scores)
    print("Mean: ", scores.mean())
    print("Standard Deviation: ", scores.std())

In [58]:
print_scores(lin_rmse)

Scores are : 1.1994570667391529
Mean:  1.1994570667391529
Standard Deviation:  0.0


# Saving the model

In [59]:
from joblib import dump, load
dump(model, "Dragon.joblib")

['Dragon.joblib']

# Testing the model on test data

In [60]:
x_test = strat_test_set.drop("MEDV", axis =1)
y_test = strat_test_set['MEDV'].copy()
x_test_prepared = my_pipeline.transform(x_test)
final_predictions = model.predict(x_test_prepared)
final_mse = mean_squared_error(y_test, final_predictions)
final_rmse = np.sqrt(final_mse)

In [61]:
final_rmse

2.8824915250797973

In [62]:
prepared_data[0]

array([-0.43942006,  3.12628155, -1.12165014, -0.27288841, -1.42262747,
       -0.24456546, -1.31238772,  2.61111401, -1.0016859 , -0.5778192 ,
       -0.97491834,  0.41164221, -0.86091034])